services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cbt_platform'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_USER=cbt_platform'
    ports:
      - '127.0.0.1::5432'
    tmpfs:
      - '/var/lib/postgresql/data'
