FROM eclipse-temurin:21-jre-noble@sha256:7739f0ffce786528961eea6bf46d9610ee968ac6127c9b2e93494757bdecce9f

WORKDIR /application
COPY build/libs/cbt-platform-0.0.1-SNAPSHOT.jar application.jar

USER 10001:10001
ENTRYPOINT ["java", "-jar", "/application/application.jar"]
