DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_iam') THEN
        CREATE ROLE app_iam;
    END IF;
END
$$;

ALTER ROLE app_iam WITH NOLOGIN NOINHERIT;
REVOKE ALL ON SCHEMA iam FROM PUBLIC;
GRANT USAGE ON SCHEMA iam TO app_iam;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA iam TO app_iam;
