package org.meldtech.migrationverify.core;

public enum StatementKind {
    CREATE_TABLE,
    CREATE_EXTENSION,
    CREATE_FUNCTION,
    CREATE_TRIGGER,
    CREATE_POLICY,
    ROW_LEVEL_SECURITY,
    ADD_COLUMN,
    ADD_CONSTRAINT,
    CREATE_INDEX,
    VALIDATE_CONSTRAINT,
    SET_DEFAULT,
    DROP_COLUMN,
    DROP_CONSTRAINT,
    DROP_DEFAULT,
    DROP_INDEX,
    DROP_TABLE,
    RENAME_COLUMN,
    COMMENT,
    GRANT,
    REVOKE,
    INVOKE_FUNCTION,
    PROCEDURAL_BLOCK,
    DATA_MODIFICATION,
    OTHER
}
