package org.meldtech.platform.migration.telemetry;

public enum MigrationRejectionCode {
    DDL_SHAPE_NOT_ALLOWED,
    COLUMN_RENAME_FORBIDDEN,
    COLUMN_DROP_BEFORE_CONTRACT,
    NOT_NULL_WITHOUT_DEFAULT,
    BLOCKING_CRITICAL_ALTER,
    NON_CONCURRENT_INDEX,
    FOREIGN_SCHEMA_ACCESS,
    CONCURRENT_INDEX_REQUIRED,
    TRANSACTIONAL_SCRIPT_REQUIRED,
    CONSTRAINT_MUST_BE_NOT_VALID,
    MULTIPLE_ALTER_OPERATIONS,
    CASCADE_NOT_ALLOWED,
    ORPHAN_COMMENT
}
